### ISSUE TITLE
Interactive Video app does not retain questions

### ISSUE THREAD

**Issue by davideveland** [tsugiproject/tsugi#174] opened 2023-09-13 14:13 UTC
When using the Interactive Video app, the authoring interface does not appear to retain questions once authored, for YouTube or Warpwire videos. Upon saving the question (it appears to save the question), the questions do not appear on the right hand editing pane as they have in the past. Oddly though a student (user) can take the quiz, but the results page show the following set of errors in the results page:
"Deprecated: Implicit conversion from float 0.11666666666666667 to int loses precision in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/util/IVUtil.php on line 23"

<img width="966" alt="Screenshot 2023-09-13 at 10 13 15 AM" src="https://github.com/tsugiproject/tsugi/assets/26579902/557be528-fe01-48ca-8b88-dabc44b28107">

**Comment by ottenhoff** [comment] 2023-09-13 14:32
I can't find this code

**Comment by davideveland** [comment] 2023-09-13 16:28
Here’s what I see on the front end:

https://somup.com/c0QIDuAMhz

From: Sam Ottenhoff ***@***.***>
Date: Wednesday, September 13, 2023 at 10:33 AM
To: tsugiproject/tsugi ***@***.***>
Cc: davideveland ***@***.***>, Author ***@***.***>
Subject: Re: [tsugiproject/tsugi] Interactive Video app does not retain questions (Issue #174)

I can't find this code

**Comment by davidpbauer** [comment] 2023-09-13 16:53
It looks like this was caused by the PHP 8.1 upgrade. The fix would need to be made in the interactive video tool itself. We're not experiencing this locally, so I can try to push any missing changes to https://github.com/udaytonapps/interactivevideo-quiz

**Comment by davidpbauer** [comment] 2023-09-13 18:32
I just pushed changes that should fix the save issues and the warning. A database upgrade may need to be run after the changes are pulled in because we also made a few other improvements that were part of the merge.

**Comment by csev** [comment] 2023-09-13 19:07
This is now deployed on www.tsugicloud.org and db changes have been run - you can test it here.

https://www.tsugicloud.org/tsugi/store/details/interactivevideo-quiz

**Comment by davidpbauer** [comment] 2023-09-13 19:25
Thanks! I just found another missed PHP 8.2 related issue and pushed a fix. Will that additional fix be pulled automatically or something you need to do yourself?

**Comment by csev** [comment] 2023-09-13 20:02
Normally it is automatic but for a little while after the 8.2 upgrade it is manual so I can keep a finger on it.   But in a few weeks it will be back to automatic  You are welcome to ping me any time to trigger a pull.

**Comment by davidpbauer** [comment] 2023-09-13 20:18
Thanks! Looks like that did the trick and it's working as expected again.

@davideveland are you able to confirm that it's working? You will most likely need to clear your browser cache before testing.

**Comment by davideveland** [comment] 2023-09-15 11:59
I'll check it out and report back.

**Comment by davideveland** [comment] 2023-09-15 15:29
Um. I went to our production and it still does not work, but thew a different error after attempting to add the tool (interactive video)- I hadn't even selected to specify the video yet, only just added the tool entry to the lessons page:

Fatal error: Uncaught Error: Call to undefined method Tsugi\Core\LTIX::getLatestHistoryIds() in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php:140 Stack trace: #0 {main} thrown in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php on line 140


![Screenshot 2023-09-15 at 11 28 06 AM](https://github.com/tsugiproject/tsugi/assets/26579902/964e79bb-1687-40ef-be26-942378b80ffa)


I then went directly to TsugiCloud to test it there, and while attempting to replace the video got the following error and can't seem to recover:

Fatal error: Uncaught Error: Call to undefined method Tsugi\Core\LTIX::getLatestHistoryIds() in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php:140 Stack trace: #0 {main} thrown in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php on line 140
![Screenshot 2023-09-15 at 11 26 47 AM](https://github.com/tsugiproject/tsugi/assets/26579902/a9f1a4d8-522e-44b2-96fd-daf24b64cbe1)

This was as of this morning Sept. 15, 2023 around 11:30am EST using sakai.lampschools.org and TsugiCloud.

**Comment by csev** [comment] 2023-09-15 15:46
This looks like it might be a Dayton specific addition to LTIX.  I am not at a computer for a few hours but when I get connected I will take a look.Sent from my iPhone On Sep 15, 2023, at 11:29 AM, davideveland ***@***.***> wrote:﻿
Um. I went to our production and it still does not work, but thew a different error after attempting to add the tool (interactive video)- I hadn't even selected to specify the video yet, only just added the tool entry to the lessons page:
Fatal error: Uncaught Error: Call to undefined method Tsugi\Core\LTIX::getLatestHistoryIds() in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php:140 Stack trace: #0 {main} thrown in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php on line 140

I then went directly to TsugiCloud to test it there, and while attempting to replace the video got the following error and can't seem to recover:
Fatal error: Uncaught Error: Call to undefined method Tsugi\Core\LTIX::getLatestHistoryIds() in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php:140 Stack trace: #0 {main} thrown in /var/www/sites/www.tsugicloud.org/mod/interactivevideo-quiz/index.php on line 140

This was as of this morning Sept. 15, 2023 around 11:30am EST using sakai.lampschools.org and TsugiCloud.

**Comment by davidpbauer** [comment] 2023-09-15 16:08
Sorry about that! I believe that function was added to LTIX to assist with auto import of interactive video content upon import/duplication in Sakai. I can take a look and either contribute the function or remove the feature.

**Comment by csev** [comment] 2023-09-15 16:16
Let’s add the function Sent from my iPhone On Sep 15, 2023, at 12:08 PM, David P. Bauer ***@***.***> wrote:﻿
Sorry about that! I believe that function was added to LTIX to assist with auto import of interactive video content upon import/duplication in Sakai. I can take a look and either contribute the function or remove the feature.

**Comment by davidpbauer** [comment] 2023-09-15 17:04
Created a PR to add the function. Drew Niekamp was the original author. I can go ahead and merge it or let it sit if you'd like to take a look.

**Comment by csev** [comment] 2023-09-15 17:09
I will take a look.   There is a weird process to make sure Tsugi-php gets updated.   I am still indisposed for a few more hours.Sent from my iPhone On Sep 15, 2023, at 1:04 PM, David P. Bauer ***@***.***> wrote:﻿
Created a PR to add the function. Drew Niekamp was the original author. I can go ahead and merge it or let it sit if you'd like to take a look.

**Comment by csev** [comment] 2023-09-16 02:37
I merged this and moved it across all the repos it needs to be.   @davideveland  - Could you take another look?

**Comment by davideveland** [comment] 2023-09-17 01:56
It works!


From: Charles Severance ***@***.***>
Date: Friday, September 15, 2023 at 10:38 PM
To: tsugiproject/tsugi ***@***.***>
Cc: davideveland ***@***.***>, Mention ***@***.***>
Subject: Re: [tsugiproject/tsugi] Interactive Video app does not retain questions (Issue #174)

I merged this and moved it across all the repos it needs to be. @davideveland<https://github.com/davideveland> - Could you take another look?

**Closed** 2023-09-17 18:59 UTC
